### PR TITLE
Feature/js flag

### PR DESCRIPTION
**Pull request by abhstabs**

### CODE REVIEW

**Comment by abhstabs** [comment]
@khemrajrathore

**Comment by ojaswa1942** [comment]
Hi, why do we need this in OSS CLI?

**Comment by abhstabs** [comment]
@ojaswa1942 Yes. Please refer DM-1739.

**Comment by ojaswa1942** [comment]
Yes, I see that we do not plan to make this public. In which case, let's keep it in `feature/js-flag` branch itself and not make it a part of `dev`. As there are no separate releases for `dev` for Privado-CLI, we can build from either branch.

**Review by ojaswa1942 — CHANGES_REQUESTED** [review]
Please make the following changes in case we wish to merge them further:

1. Add another flag for applying experimental flags, `enable-experiments`, which will enable reading all experimental flags
2. Rename the flag to `enable-javascript` and prefix the description with `Experimental: `



To apply, the user must pass both, like `--enable-experiments --enable-javascript`.

In case any experimental flag is specified without `--enable-experiments`, raise an error. The idea is to apply any experimental flags only when experiments are explicitly enabled.

With these changes, we can also ship it for release if required.

**Review by ojaswa1942 — APPROVED** [review]
@abhstabs Thanks for making the changes. The experimental features look consistent with other CLI tools out there! :shipit:

**Comment by ojaswa1942** [comment]
@abhstabs Can you also create a corresponding issue on Privado and link the PRs for `cli` and `core`?

**Comment by abhstabs** [comment]
Related to issue https://github.com/Privado-Inc/privado/issues/97

**Review by pandurangpatil — APPROVED** [review]
looks good to me.

**Pull request merged**
